Add cutout_to_black integration tests
jhuapl-boss/spdb pull request #27
Opened 2021-03-16 21:01 UTC by dxenes1

This PR adds an additional unit and integration tests.

After merging the cutout-to-black fixes (https://github.com/jhuapl-boss/spdb/pull/24),  I wanted to create more robust tests to ensure that modifying the write_cuboid_keys does not affect cache and delayed write operations. 

From what I can see, the current rediskvio does not have to be modified since the modification to the write_cuboid_key does not change the parsing of its individual components. What I mean by that is that traditionally a write cuboid key would be something like 

`WRITE-CUBOID&{lookup_key}&time_sample&morton_id&UUID`

The KVIO functions split the key by the `&` characters and get the information it needs to construct the cache key. For black-upload cuboids the same structure is used but just a different prefix.

`BLACK-CUBOID&{lookup_key}&time_sample&morton_id&UUID`

Since the information order is preserved, KVIO works with these keys without any issues. The lambda can then identify its a black cuboid from the prefix. However, from these tests I did find a bug in s3_flush lambda that I will submit another PR for!

2021-03-17 20:34 UTC, movestill requested changes

2021-03-17 20:34 UTC, movestill commented on spdb/spatialdb/test/int_test_spatialdb.py
> +        expected_data[:, :self.z_dim//2, :, :] = 0
Not a biggie since this happens at the very end of the test, but you are actually mutating `cube1.data` here.

2021-03-17 20:34 UTC, movestill commented on spdb/spatialdb/test/test_rediskvio.py
> +        assert keys[0].rsplit("&", 1)[0] == "BLACK-CUBOID&4&3&2&2&0&34"
Maybe you should test all 9 keys for completeness?

2021-06-29 17:35 UTC, sandyhider approved these changes

2021-06-30 10:22 UTC, merged